version: "3.8"

volumes:
  db:

services:
  db:
    image: postgres:14
    init: true
    environment:
      POSTGRES_USER: iscc
      POSTGRES_PASSWORD: generator
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: .
      target: dev-runtime-backend
    init: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://iscc:generator@db/iscc
      AUTO_MIGRATE: "true"
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/app

  worker:
    build:
      context: .
      target: dev-runtime-worker
    init: true
    depends_on:
      - db
      - backend
    environment:
      DATABASE_URL: postgres://iscc:generator@db/iscc
    volumes:
      - .:/app
