# Generated by Django 4.0.2 on 2022-02-17 08:04

from django.db import migrations, models
import django.utils.timezone
import iscc_generator.models
import iscc_generator.utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IsccCode",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.PositiveBigIntegerField(
                        default=iscc_generator.utils.make_flake,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "iscc",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="International Standard Content Code",
                        max_length=73,
                        verbose_name="ISCC",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        default="",
                        help_text="The file used for generating the ISCC",
                        upload_to=iscc_generator.models.hash_name,
                        verbose_name="source file",
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Original filename from upload (autoset / untrusted)",
                        max_length=255,
                        verbose_name="filename",
                    ),
                ),
                (
                    "source_file_mediatype",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Original IANA Media Type (MIME type) from upload (autoset / untrusted)",
                        max_length=255,
                        verbose_name="mediatype",
                    ),
                ),
                (
                    "source_file_size",
                    models.PositiveBigIntegerField(
                        editable=False,
                        help_text="The filesize of the media asset",
                        null=True,
                        verbose_name="filesize",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of file used for generating the ISCC",
                        max_length=4096,
                        verbose_name="source_url",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The title or name of the work manifested by the media asset. Used as input for the ISCC Meta-Code",
                        max_length=128,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the digital content identified by the ISCC. Used as input for the ISCC Meta-Code",
                        max_length=4096,
                        verbose_name="description",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="The result returned by the ISCC generator",
                        null=True,
                        verbose_name="result",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISCC Code",
                "verbose_name_plural": "ISCC Codes",
            },
        ),
    ]
