# Generated by Django 4.0.3 on 2022-03-10 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import iscc_generator.base
import iscc_generator.storage
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IsccCode",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.PositiveBigIntegerField(
                        default=iscc_generator.base.make_flake,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "iscc",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="International Standard Content Code",
                        max_length=73,
                        verbose_name="ISCC",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        default="",
                        help_text="The file used for generating the ISCC",
                        upload_to=iscc_generator.storage.get_storage_path,
                        verbose_name="source file",
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Original filename from upload (autoset / untrusted)",
                        max_length=255,
                        verbose_name="filename",
                    ),
                ),
                (
                    "source_file_mediatype",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Original IANA Media Type (MIME type) from upload (autoset / untrusted)",
                        max_length=255,
                        verbose_name="mediatype",
                    ),
                ),
                (
                    "source_file_size",
                    models.PositiveBigIntegerField(
                        default=0,
                        editable=False,
                        help_text="The filesize of the media asset",
                        null=True,
                        verbose_name="filesize",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL of file used for generating the ISCC",
                        max_length=4096,
                        verbose_name="source_url",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The title or name of the work manifested by the media asset. Used as input for the ISCC Meta-Code",
                        max_length=128,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the digital content identified by the ISCC. Used as input for the ISCC Meta-Code",
                        max_length=4096,
                        verbose_name="description",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Metadata for Meta-Code",
                        null=True,
                        verbose_name="metadata",
                    ),
                ),
                (
                    "embed",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Fields for embedding",
                        null=True,
                        verbose_name="embed",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="The result returned by the ISCC generator",
                        null=True,
                        verbose_name="result",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISCC Code",
                "verbose_name_plural": "ISCC Codes",
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.PositiveBigIntegerField(
                        default=iscc_generator.base.make_flake,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Original filename from upload (untrusted)",
                        max_length=255,
                        verbose_name="filename",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        help_text="The actual media asset",
                        null=True,
                        upload_to=iscc_generator.storage.get_storage_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Original IANA Media Type (MIME type) from upload (untrusted)",
                        max_length=255,
                        verbose_name="mediatype",
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        editable=False,
                        help_text="The filesize of the media asset",
                        null=True,
                        verbose_name="filesize",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Metadata embedded in the file",
                        null=True,
                        verbose_name="metadata",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        default=None,
                        help_text="Original media object if derived",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iscc_generator.media",
                        verbose_name="original",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Asset",
            },
        ),
    ]
