# Generated by Django 4.0.2 on 2022-02-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iscccode",
            name="embed",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Fields for embedding",
                null=True,
                verbose_name="embed",
            ),
        ),
        migrations.AddField(
            model_name="iscccode",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Metadata for Meta-Code",
                null=True,
                verbose_name="metadata",
            ),
        ),
    ]
