# Generated by Django 4.0.3 on 2022-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0002_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="iscccode",
            name="acquire",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL for acquiring a license for the digital content.",
                max_length=4096,
                verbose_name="acquire",
            ),
        ),
        migrations.AddField(
            model_name="iscccode",
            name="license",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of license for the digital content.",
                max_length=4096,
                verbose_name="license",
            ),
        ),
    ]
