# Generated by Django 4.0.3 on 2022-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0002_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iscccode",
            name="meta",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Subject, industry, or use-case specific metadata, encoded as JSON string or Data-URL (used as sole input for Meta-Code and `metahash` generation if supplied).",
                max_length=16384,
                verbose_name="meta",
            ),
        ),
    ]
