# Generated by Django 4.0.3 on 2022-03-15 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import iscc_generator.base
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0003_alter_iscccode_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nft",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.PositiveBigIntegerField(
                        default=iscc_generator.base.make_flake,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chain",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            ("PRIVATE", "Private"),
                            ("BITCOIN", "Bitcoin"),
                            ("ETHEREUM", "Ethereum"),
                            ("POLYGON", "Polygon"),
                        ],
                        default="",
                        help_text="The blockchain on which the ISCC-CODE will be declared.",
                        max_length=32,
                        verbose_name="chain",
                    ),
                ),
                (
                    "wallet",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The wallet-address that will sign the ISCC declaration.",
                        max_length=128,
                        verbose_name="wallet",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="NFT attributes to be shown on marketplaces",
                        null=True,
                        verbose_name="attributes",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="External URL to be shown on marketplaces",
                        max_length=4096,
                        verbose_name="external url",
                    ),
                ),
                (
                    "redirect",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to which an ISCC resolver should redirect for the registered ISCC-ID",
                        max_length=4096,
                        verbose_name="redirect",
                    ),
                ),
                (
                    "original",
                    models.BooleanField(
                        default=None,
                        help_text="Whether the signee claims to be the original creator of the digital content",
                        null=True,
                        verbose_name="original",
                    ),
                ),
                (
                    "verifications",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="A list of self-verifications (Public URLs under the authority of the signee.",
                        null=True,
                        verbose_name="verifications",
                    ),
                ),
                (
                    "iscc_code",
                    models.ForeignKey(
                        default=None,
                        help_text="ISCC-CODE of NFT",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iscc_generator.iscccode",
                        verbose_name="ISCC-CODE",
                    ),
                ),
            ],
            options={
                "verbose_name": "NFT",
            },
        ),
    ]
