# Generated by Django 4.0.2 on 2022-02-19 20:56
from django.db import migrations
from django.core.management import call_command


def load_theme(apps, schema_editor):
    call_command(
        "loaddata", "--app", "admin_interface.Theme", "admin_interface_theme_iscc"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0003_alter_iscccode_result_and_more"),
    ]

    operations = [
        migrations.RunPython(load_theme),
    ]
