# Generated by Django 4.0.3 on 2022-03-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0003_iscccode_acquire_iscccode_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iscccode",
            name="acquire",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="URL for acquiring a license for the digital content.",
                max_length=4096,
                null=True,
                verbose_name="acquire",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="description",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Description of the digital content identified by the ISCC. Used as input for the ISCC Meta-Code",
                max_length=4096,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="iscc",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                help_text="International Standard Content Code",
                max_length=73,
                null=True,
                verbose_name="ISCC",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="license",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="URL of license for the digital content.",
                max_length=4096,
                null=True,
                verbose_name="license",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="meta",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Subject, industry, or use-case specific metadata, encoded as JSON string or Data-URL (used as sole input for Meta-Code and `metahash` generation if supplied).",
                max_length=16384,
                null=True,
                verbose_name="meta",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="name",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The title or name of the work manifested by the media asset. Used as input for the ISCC Meta-Code",
                max_length=128,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="File used for ISCC-CODE creation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iscc_generator.media",
                verbose_name="souce_file",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="source_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="URL of file used for generating the ISCC-CODE",
                max_length=4096,
                null=True,
                verbose_name="source_url",
            ),
        ),
    ]
