# Generated by Django 4.0.4 on 2022-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iscc_generator", "0003_nft_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="iscccode",
            name="rights",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Copyright notice",
                max_length=1024,
                null=True,
                verbose_name="rights",
            ),
        ),
    ]
