# Generated by Django 4.0.5 on 2022-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iscc_generator", "0004_rights_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nft",
            name="nft_chain",
        ),
        migrations.RemoveField(
            model_name="nft",
            name="nft_contract",
        ),
        migrations.RemoveField(
            model_name="nft",
            name="nft_token",
        ),
        migrations.AddField(
            model_name="nft",
            name="nft",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A unique URI for NFT of the identified content (CAIP-22, CAIP-29).",
                max_length=255,
                null=True,
                verbose_name="nft",
            ),
        ),
    ]
