# Generated by Django 4.0.3 on 2022-03-17 11:50

from django.db import migrations, models
import django.db.models.deletion
import iscc_generator.storage


class Migration(migrations.Migration):

    dependencies = [
        (
            "iscc_generator",
            "0004_alter_iscccode_acquire_alter_iscccode_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="cid",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="IPFS CIDv1",
                max_length=128,
                null=True,
                verbose_name="cid",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="name",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                help_text="Original filename from upload (untrusted)",
                max_length=255,
                null=True,
                verbose_name="filename",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="original",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Original media object if derived",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iscc_generator.media",
                verbose_name="original",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="source_file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="The actual media asset",
                null=True,
                upload_to=iscc_generator.storage.get_storage_path,
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="type",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                help_text="Original IANA Media Type (MIME type) from upload (untrusted)",
                max_length=255,
                null=True,
                verbose_name="mediatype",
            ),
        ),
        migrations.AlterField(
            model_name="nft",
            name="chain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE", "Private"),
                    ("BITCOIN", "Bitcoin"),
                    ("ETHEREUM", "Ethereum"),
                    ("POLYGON", "Polygon"),
                ],
                default=None,
                help_text="The blockchain on which the ISCC-CODE will be declared.",
                max_length=32,
                null=True,
                verbose_name="chain",
            ),
        ),
        migrations.AlterField(
            model_name="nft",
            name="external_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="External URL to be shown on marketplaces.",
                max_length=4096,
                null=True,
                verbose_name="external url",
            ),
        ),
        migrations.AlterField(
            model_name="nft",
            name="iscc_code",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="ISCC-CODE of NFT.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iscc_generator.iscccode",
                verbose_name="ISCC-CODE",
            ),
        ),
        migrations.AlterField(
            model_name="nft",
            name="original",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether the signee claims to be the original creator of the digital content.",
                null=True,
                verbose_name="original",
            ),
        ),
        migrations.AlterField(
            model_name="nft",
            name="redirect",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="URL to which an ISCC resolver should redirect for the registered ISCC-ID.",
                max_length=4096,
                null=True,
                verbose_name="redirect",
            ),
        ),
        migrations.AlterField(
            model_name="nft",
            name="wallet",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The wallet-address that will sign the ISCC declaration.",
                max_length=128,
                null=True,
                verbose_name="wallet",
            ),
        ),
    ]
