# Generated by Django 4.0.3 on 2022-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0005_alter_media_cid_alter_media_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iscccode",
            name="creator",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="An entity primarily responsible for making the resource.",
                max_length=128,
                null=True,
                verbose_name="creator",
            ),
        ),
    ]
