# Generated by Django 4.0.3 on 2022-03-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0006_iscccode_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="properties",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="NFT properties to be shown on marketplaces.",
                null=True,
                verbose_name="properties",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="description",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Description of the digital content identified by the ISCC. Used as input for the ISCC Meta-Code.",
                max_length=4096,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="iscccode",
            name="result",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="The result returned by the ISCC generator.",
                null=True,
                verbose_name="result",
            ),
        ),
    ]
