# Generated by Django 4.0.3 on 2022-03-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iscc_generator", "0007_nft_properties_alter_iscccode_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nft",
            name="iscc_code",
        ),
        migrations.AddField(
            model_name="nft",
            name="media_id_animation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="ID of Media object to be used as NFT animation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nft_animation",
                to="iscc_generator.media",
                verbose_name="media animation",
            ),
        ),
        migrations.AddField(
            model_name="nft",
            name="media_id_image",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="ID of Media object to be used as NFT immage",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nft_image",
                to="iscc_generator.media",
                verbose_name="media image",
            ),
        ),
    ]
